version: '3'
services:
  backend:
    volumes:
      - ./backend:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    restart: always
    command: gunicorn -w 4 -b 0.0.0.0:5001 'app:app'

  frontend:
    volumes:
      - ./frontend:/app
      - front_node_modules:/app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # 開発用サーバで使用（本番環境で動かす場合はコメントアウト）
      - 5173:5173 
    expose:
      - 5173
    tty: true
    restart: always

  # fully automated SSL certificates
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    expose:
      - 80
    ports:
      - 80:80
    environment:
      # localでの開発用
      # STAGE: 'local'
      # DOMAINS: 'localhost'

      # 本番環境（でのテスト）用
      # STAGE: 'staging'
      # DOMAINS: 'arakawabase.com'

      # 本番環境用
      STAGE: 'production'
      DOMAINS: 'arakawabase.com'

    volumes:
      - https-portal-data:/var/lib/https-portal
      

  # 本番環境で使用
  # docker compose exec frontend npm run buildで作成されたdistをコンテナの/var/www/に配置（紐づけ）
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 443:8000
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d:/etc/nginx/conf.d
      - ./server/log:/var/log/nginx
      - ./frontend/dist:/var/www/dist
      - https-portal-data:/etc/nginx/ssl
    tty: true
    restart: always

volumes:
  front_node_modules:
  https-portal-data:

